# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=50)),
                ('image_caption', models.CharField(max_length=600)),
            ],
        ),
    ]
