# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200601_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='body',
        ),
    ]
