# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200601_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='image_likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='image_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
